#!/usr/bin/env node
/**
 * Assembles the static asset layout that wrangler uploads (architecture section 9.1).
 *
 * Three directories, three producers, no cross-references:
 *   public/theme   theme assets and the site stylesheet   (packages/themes/*)
 *   public/static  prerendered HTML                       (static export, backlog)
 *   public/admin   the React admin SPA                    (apps/admin)
 *
 * None of those producers exists yet, so this script creates the layout, writes
 * the cache policy, and reports which directories are still empty. The layout is
 * the contract; filling it is later work.
 */
import { mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')
const publicDir = join(root, 'public')

const directories = ['theme', 'static', 'admin']
for (const directory of directories) {
  mkdirSync(join(publicDir, directory), { recursive: true })
}

/**
 * Workers Static Assets serves these paths without ever invoking the Worker, so
 * the cache policy has to live here rather than in code (section 2.1: whatever
 * can be static should cost nothing).
 *
 * `admin/index.html` must never be cached, or a deploy would keep handing out the
 * previous shell and its hashed asset names. The hashed files beside it are
 * immutable and can be cached forever.
 *
 * The shell needs two rules: `_headers` matches the request path, not the file
 * the asset store resolved to, so a request for the directory and a request for
 * the file are different keys.
 */
const headers = `# Generated by scripts/build-site.mjs -- do not edit by hand.

/admin/
  Cache-Control: no-cache

/admin/index.html
  Cache-Control: no-cache

/admin/assets/*
  Cache-Control: public, max-age=31536000, immutable

/theme/*
  Cache-Control: public, max-age=3600
`
writeFileSync(join(publicDir, '_headers'), headers, 'utf8')

function countFiles(directory) {
  let count = 0
  for (const entry of readdirSync(directory)) {
    const full = join(directory, entry)
    count += statSync(full).isDirectory() ? countFiles(full) : 1
  }
  return count
}

for (const directory of directories) {
  const count = countFiles(join(publicDir, directory))
  const note = count === 0 ? ' (producer has not run yet)' : ''
  console.log(`  public/${directory}: ${count} file(s)${note}`)
}

console.log('build:site -- public/_headers written')
