import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * Turns the theme's Liquid files into the baseline module the Worker imports.
 *
 * The alternative -- reading `.liquid` files at runtime -- would mean the Worker
 * filesystem, which does not exist, or a bundler-specific import that only one
 * bundler understands. Compiling at build time keeps the templates as templates
 * (editable, diffable, and the thing a theme author actually writes) while the
 * Worker gets a plain object.
 *
 * Run `pnpm theme:generate` after editing a template. `pnpm check:theme-drift`
 * is what stops the generated module from going stale in a commit: it fails when
 * the files and the module disagree, the same way the schema check does.
 */

const ROOT = join(import.meta.dirname, '..')
const DIRECTORIES = ['layouts', 'templates', 'snippets'] as const
const OUTPUT = join(ROOT, 'src', 'baseline.ts')

/**
 * The key a template is stored under.
 *
 * The extension goes, because that is how the loader looks names up: a template
 * asks for `snippets/header`, not for a file. Keeping the two in step here means
 * the baseline's keys are exactly the set the loader will accept.
 */
function toKey(path: string): string {
  return path.endsWith('.liquid') ? path.slice(0, -'.liquid'.length) : path
}

function collect(): Record<string, string> {
  const templates: Record<string, string> = {}

  for (const directory of DIRECTORIES) {
    for (const file of readdirSync(join(ROOT, directory)).sort()) {
      if (!file.endsWith('.liquid')) continue
      templates[toKey(`${directory}/${file}`)] = readFileSync(join(ROOT, directory, file), 'utf8')
    }
  }

  return templates
}

function render(templates: Record<string, string>): string {
  const entries = Object.entries(templates)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, source]) => `  ${JSON.stringify(key)}: ${JSON.stringify(source)},`)
    .join('\n')

  return [
    '/**',
    ' * Generated by `pnpm theme:generate`. Do not edit.',
    ' *',
    ' * The baseline theme, as the Worker sees it: normalised name to source. The',
    ' * keys are the complete set of templates the admin may edit -- an override',
    ' * cannot introduce a name the theme does not ship, which is what makes the',
    ' * whitelist check a memory lookup rather than a prefix test.',
    ' */',
    '',
    'export const BASELINE: Record<string, string> = {',
    entries,
    '}',
    '',
    '/** The names, in the order a browser should show them. */',
    'export const BASELINE_NAMES: string[] = Object.keys(BASELINE)',
    '',
  ].join('\n')
}

const expected = render(collect())
const command = process.argv[2] ?? 'check'

if (command === 'generate') {
  writeFileSync(OUTPUT, expected)
  console.log(`theme:generate -- wrote ${OUTPUT.replace(`${ROOT}/`, '')}`)
} else {
  let actual = ''

  try {
    actual = readFileSync(OUTPUT, 'utf8')
  } catch {
    console.error('theme:check -- src/baseline.ts is missing. Run `pnpm theme:generate`.')
    process.exit(1)
  }

  if (actual !== expected) {
    console.error('theme:check -- src/baseline.ts is out of date.')
    console.error('  The .liquid files and the generated module disagree.')
    console.error('  Run `pnpm theme:generate` and commit the result.')
    process.exit(1)
  }

  console.log('theme:check -- the baseline and the generated module agree')
}
